export let ADD_INBOX_TASK = "ADD_INBOX_TASK";
export let REMOVE_INBOX_TASK = "REMOVE_INBOX_TASK";
export let EDIT_INBOX_TASK = "EDIT_INBOX_TASK";
export let MAKE_INBOX_TASK_TO_IMPORTANT = "MAKE_INBOX_TASK_TO_IMPORTANT";
